name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Build image
    runs-on: [ubuntu-latest]

    steps:
    - name: Get current date
      id: builddate
      run: echo "::set-output name=date::$(date +'%m/%d/%Y')"

    - name: remove NGing Auth 
      id: nginx-auth-remove
      run: | 
            pwd 
            cat nginx/default.conf
      shell: bash
