name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Build image
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get current date
      id: builddate
      run: |
         ed -s nginx/default.conf <<< $'10,1d\nw'
         cat  nginx/default.conf
      shell: bash

    - name: remove NGing Auth 
      id: nginx-auth-remove
      run: echo $PATH          
      shell: bash
