name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Build image
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get current date
      id: builddate
      run: |
         echo $PWD  
         ls ${{ github.workspace }}
         cd nginx
         ls
         ed -s default.conf <<< $'g/auth_basic "Authenticated Access";/d\nw'
         ed -s default.conf <<< $'g/auth_basic "auth_basic_user_file";/d\nw'
         cat default.conf
      shell: bash

    - name: remove NGing Auth 
      id: nginx-auth-remove
      run: echo $PATH          
      shell: bash
