name: Build and Deploy to STAGE

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    name: Build and Push to STAGE Environment
    runs-on: [self-hosted, linux, x64, ec2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

          echo test, and deploy your project.
