name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Build image
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Nginx Remove Auth
      id: nginx-auth
      run: |
         sed -e '10d;11d' nginx/default.conf
         cat  nginx/default.conf
      shell: bash
