name: Build and Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and Push to Dev Environment
    runs-on: [self-hosted, linux, x64, ec2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: builddate
        run: echo "::set-output name=date::$(date +'%m/%d/%Y')"